### ISSUE TITLE
Bug: apostrophe in exposure name breaks the sql statement

### ISSUE THREAD

**Issue by smitsrr** [brooklyn-data/dbt_artifacts#180]
We scrape our exposure names from our tableau server, so there may be non-traditional or special characters. 

In this instance, the insert-statement fails because of an apostrophe in the exposure name.
Offending record:
```
insert into dwh.meta_dbt.exposures
    
        select
            $1,
            $2,
            $3,
            $4,
            $5,
            parse_json($6),
            $7,
            $8,
            $9,
            $10,
            $11,
            parse_json($12)
        from values (
                'aa23a21f-dbb9-4b6b-8d31-a9e8cb68a750', 
                'exposure.dbt_marts.Brenna's Request', 
                '2022-08-19 12:03:44.864734+00:00', 
                'Brenna's Request', 
                'notebook', 
                '{"email": "dd@tripactions.com", "name": "dd"}', 
                'None', 
                '☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺_tableau.yml', 
                '', 
                'None', 
                'dbt_marts', 
                '["model.dbt_marts.company_ebum_activity_daily", "model.dbt_marts.liquid_transactions", "model.dbt_marts.mart_booking", "model.dbt_marts.mart_user"]' 
            ),(
```

Potential solutions
1. Similar to how there is a replace on the path name, we could add an escape on the exposure name. 
2. Do number one, but also exclude other potential problematic characters (not sure what would be as problematic though). 
3. Allow users to exclude the exposure insert statement

**Comment by jaypeedevlin** [comment]
I think this is fixed by https://github.com/brooklyn-data/dbt_artifacts/pull/170, released in 1.1.2.  What version of the package are you using?

**Comment by smitsrr** [comment]
oh shoot! I upgraded to 1.1.1. I'll update today!

**Comment by smitsrr** [comment]
That PR doesn't resolve the issue - our issue manifests in the `exposure.id` and `exposure.name` fields. We just need to apply that same replace statement to those items though so it should be quick.

**Comment by jaypeedevlin** [comment]
Thanks for correcting me, and apologies that I didn't quite capture the detail in the original.  Since this seems like a simple fix I've raised a PR.

**Comment by smitsrr** [comment]
Resolved, now waiting for a release with this fix.
