### ISSUE TITLE
fct_dbt__critical_path is not showing the slowest path

### ISSUE THREAD

**Issue by john-jerome** [brooklyn-data/dbt_artifacts#52]
Hey there!
We've been collecting dbt artifacts for a while now and already back when we started I noticed that the `fct_dbt__critical_path` table looked very suspicious (i.e. too good to be true) in our case, and it still does:
![Screenshot 2021-10-13 at 10 14 37](https://user-images.githubusercontent.com/31763328/137094310-37f67567-e28e-4d0e-83d5-315e5178b660.png)

I tried to investigate this issue by looking at the structure of the `fct_dbt__critical_path` model and it seems that everything until [`search_path (node_ids, total_time)`](https://github.com/tailsdotcom/dbt_artifacts/blob/27d81ab6277490578a075830ee1c235e0d8e0438/models/fct_dbt__critical_path.sql#L156) produces the expected results (in particular, in our case). I was just confused by the fact that `total_time` column seems to be a string instead of float. However, starting with the next CTE called [`longest_path_node_ids` ](https://github.com/tailsdotcom/dbt_artifacts/blob/27d81ab6277490578a075830ee1c235e0d8e0438/models/fct_dbt__critical_path.sql#L175) we are getting the wrong node sequence. There must be something that this `case when` does that I don't understand.

Any help would be appreciated!

**Comment by NiallRees** [comment]
Hey John - I think this should have been fixed by https://github.com/tailsdotcom/dbt_artifacts/pull/51. It hasn't been released yet, but could you try installing the latest commit to see if that fixes things?

`packages.yml`
```
  - git: "https://github.com/tailsdotcom/dbt_artifacts.git"
```

**Comment by GenDemo** [comment]
I am also still having this problem, and I installed last week.

**Comment by NiallRees** [comment]
> I am also still having this problem, and I installed last week.

Please could you provide a screenshot of the model and share which version of dbt_artifacts you have installed?

**Comment by GenDemo** [comment]
Hi @NiallRees 

Thnx for getting back to me.
Sure, please see below:

![image](https://user-images.githubusercontent.com/58798533/147037068-2313dfca-9c4e-49a2-9139-6adf092c4902.png)

![image](https://user-images.githubusercontent.com/58798533/147037121-ddd6406a-cf2a-4585-b22c-08992d273d3d.png)
![image](https://user-images.githubusercontent.com/58798533/147037136-e7d1df71-d30f-4a21-bb6a-e82459401072.png)

**Comment by NiallRees** [comment]
@GenDemo The latest version of the package is 0.6.0, could you give that a try?

**Comment by GenDemo** [comment]
Definitely - Today is my last day for the Christmas break, so it will be a while before I reply.

**Comment by GenDemo** [comment]
Cool, that seems to have worked!  thnx  :)
